name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: todo
        run: make

      - name: Build test
        run: make test

      - name: Run test
        run: bin/test
        run: Name
        run: Description
        run: ~
        run: 1
        run: 1
        run: 2020
        run: ***
        run: Category
        run: 10